# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: onlishop-cli
    ldflags: -s -w -X 'github.com/onlishop/onlishop-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: '386'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - completions/*

release:
  github:
    owner: onlishop
    name: onlishop-cli

dockers_v2:
  - id: php-84
    images:
      - "onlishop/onlishop-cli"
      - "ghcr.io/onlishop/onlishop-cli"
    tags:
      - "{{ .Version }}-php-8.4"
      - "latest-php-8.4"
    build_args:
      PHP_VERSION: "8.4"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
  - id: php-83
    images:
      - "onlishop/onlishop-cli"
      - "ghcr.io/onlishop/onlishop-cli"
    tags:
      - "{{ .Version }}-php-8.3"
      - "latest-php-8.3"
      - "{{ .Version }}"
      - "latest"
    build_args:
      PHP_VERSION: "8.3"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
  - id: php-82
    images:
      - "onlishop/onlishop-cli"
      - "ghcr.io/onlishop/onlishop-cli"
    tags:
      - "{{ .Version }}-php-8.2"
      - "latest-php-8.2"
    build_args:
      PHP_VERSION: "8.2"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
  - id: php-81
    images:
      - "onlishop/onlishop-cli"
      - "ghcr.io/onlishop/onlishop-cli"
    tags:
      - "{{ .Version }}-php-8.1"
      - "latest-php-8.1"
    build_args:
      PHP_VERSION: "8.1"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
  - id: bin
    images:
      - "onlishop/onlishop-cli"
      - "ghcr.io/onlishop/onlishop-cli"
    dockerfile: Dockerfile.bin
    tags:
      - "bin-{{ .Version }}"
      - "bin"
    platforms:
      - "linux/amd64"
      - "linux/arm64"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: checksum
    args:
    - "sign-blob"
    - "--output-certificate=${certificate}"
    - "--output-signature=${signature}"
    - '${artifact}'
    - "--yes"

docker_signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    artifacts: all
    args:
    - 'sign'
    - '${artifact}'
    - "--yes"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request:'
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🧰 Maintenance
      order: 999

aurs:
  - homepage: https://developer.onlishop.com/
    description: A cli which contains handy helpful commands for daily Onlishop tasks
    license: MIT
    maintainers:
      - "Soner Sayakci <s.sayakci@onlishop.com>"
      - "Max <max@swk-web.com>"
    private_key: '{{ .Env.AUR_KEY }}'
    commit_author:
      name: "Onlishop Bot"
      email: github@onlishop.com
    git_url: 'ssh://aur@aur.archlinux.org/onlishop-cli-bin.git'
    depends:
      - "git"
    package: |-
      install -Dm755 "./onlishop-cli" "${pkgdir}/usr/bin/onlishop-cli"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/onlishop-cli/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/onlishop-cli.bash" "${pkgdir}/usr/share/bash-completion/completions/onlishop-cli"
      install -Dm644 "./completions/onlishop-cli.zsh" "${pkgdir}/usr/share/zsh/site-functions/_onlishop-cli"
      install -Dm644 "./completions/onlishop-cli.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/onlishop-cli.fish"

nix:
  - name: onlishop-cli
    repository:
      owner: FriendsOfOnlishop
      name: nur-packages
      branch: main
      token: "{{ .Env.NUR_GITHUB_TOKEN }}"
    commit_author:
      name: "Onlishop Bot"
      email: github@onlishop.com
    post_install: |
      installShellCompletion --cmd onlishop-cli \
      --bash <($out/bin/onlishop-cli completion bash) \
      --zsh <($out/bin/onlishop-cli completion zsh) \
      --fish <($out/bin/onlishop-cli completion fish)
    homepage: "https://sw-cli.fos.gg"
    description: "Command line tool for Onlishop 6"
    license: "mit"

nfpms:
  -
    package_name: onlishop-cli
    vendor: "onlishop AG"
    homepage: https://github.com/onlishop/onlishop-cli/
    maintainer: Soner Sayakci <s.sayakci@onlishop.com>
    description: A cli which contains handy helpful commands for daily Onlishop tasks
    license: MIT
    contents:
      - src: ./completions/onlishop-cli.bash
        dst: /etc/bash_completion.d/onlishop-cli
      - src: ./completions/onlishop-cli.fish
        dst: /usr/share/fish/completions/onlishop-cli.fish
      - src: ./completions/onlishop-cli.zsh
        dst: /usr/local/share/zsh/site-functions/_onlishop-cli
    formats:
      - apk
      - deb
      - rpm

homebrew_casks:
  - name: onlishop-cli
    repository:
      owner: onlishop
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN_ONLISHOP }}"
    commit_author:
      name: Frosh Automation
      email: ci@fos.gg
    homepage: https://onlishop.com
    description: Onlishop CLI helps Onlishop developers manage extensions
    license: MIT
    completions:
      bash: completions/onlishop-cli.bash
      zsh: completions/onlishop-cli.zsh
      fish: completions/onlishop-cli.fish

npms:
  - name: "@onlishop-ag/onlishop-cli"
    description: "Onlishop CLI helps Onlishop developers manage extensions"
    license: MIT
    homepage: https://developer.onlishop.com/docs/products/cli/
    keywords:
      - cli
      - onlishop
    repository: https://github.com/onlishop/onlishop-cli
    bugs: https://github.com/onlishop/onlishop-cli/issues
    access: public

notarize:
  macos:
    - enabled: '{{ isEnvSet "APPLE_CODE_SIGNING_KEY" }}'
      sign:
        certificate: "{{.Env.APPLE_CODE_SIGNING_KEY}}"
        password: "{{.Env.APPLE_CODE_SIGNING_KEY_PASSWORD}}"
        entitlements: "./entitlements.xml"
      notarize:
        issuer_id: "{{.Env.APPLE_APP_STORE_CONNECT_ISSUER}}"
        key_id: "{{.Env.APPLE_APP_STORE_CONNECT_KEY_ID}}"
        key: "{{.Env.APPLE_APP_STORE_CONNECT_KEY}}"
